### PR TITLE
fix: fix the utm converter initialization

### PR DESCRIPTION
**Pull request by seixasxbr**
Depends on:
- [ ] https://github.com/rock-drivers/drivers-gps_base/pull/17

# What is this PR for
fix the utm converter initialization
[sc-45539]

# Results, How I tested
render_cam

# Checklist
- [x] Assign yourself  in the PR

### CODE REVIEW

**Review by eduardacoppo — COMMENTED** [review]
Change variable names to the current convention (snake case).

**Comment by wvmcastro** [comment]
I believe that with the fix being done in gps_base there is no need to use the unique pointer here, or am I missing something?

**Comment by seixasxbr** [comment]
> I believe that with the fix being done in gps_base there is no need to use the unique pointer here, or am I missing something?

Yes, it is needed. This class do not accept copy-initialization

**Comment by seixasxbr** [comment]
> Change variable names to the current convention (snake case).

It is not this pr purpose

**Comment by eduardacoppo** [comment]
> > Change variable names to the current convention (snake case).
> 
> It is not this pr purpose

That's irrelevant. It's a good practice to refactor if you happen to be editing code that needs the update. See https://github.com/tidewise/drivers-orogen-comms_wetpaint/pull/15/commits/2c87493157b8aa880d2a111b1d62846f37e39578 and https://github.com/tidewise/robots-orogen-wetpaint_live/pull/34/commits/241c64499a3cae5c4560005297612f6ee03159d7

**Comment by seixasxbr** [comment]
Closing, since this pr is not needed anymore, due this [fix](https://github.com/rock-drivers/drivers-gps_base/pull/17)

**Pull request closed without merging**
